### PR TITLE
fix(): add workaround for ios 12.2 scrolling bug

### PR DESCRIPTION
**Pull request by liamdebeasi**
#### Short description of what this resolves:
This PR adds a workaround for a bug in iOS 12.2 where `pointer-events: none` is not being removed from `ion-app` even though the class that sets it is removed from the DOM.

#### Changes proposed in this pull request:

- Add a raf that adds/removes `z-index: 1` on `ion-app`

**Fixes**: #984

### CODE REVIEW

**Comment by BumbleeLin** [comment]
@liamdebeasi awesome! works, is this just a work around for now?

**Comment by liamdebeasi** [comment]
Hi there,

This is an old fix to address an issue in the iOS 12.2 beta. The bug has been fixed by Apple in the release version of iOS 12.2, so this workaround is no longer needed.

**Comment by BumbleeLin** [comment]
@liamdebeasi we are using Xcode 10.2 and iOS 12.2, the issue was still occurring. Adding the workaround worked. Is there I'm perhaps not doing?

**Comment by liamdebeasi** [comment]
Ah interesting. If the workaround fixes your specific issue, feel free to keep using it!

**Comment by BumbleeLin** [comment]
@liamdebeasi cool thanks man.

**Comment by jameshuimin** [comment]
hello。"ionic-angular": "^3.9.5", the bug The bug is still in ionic3。When I run in the web（ionic cordova build browser ），Interface off screen，scroll up 2times， page will be stuck for 1-2 seconds, And then touch it again work。I checked to see if the file had changed and in node_modules/ionic-angular/es2015/components/app/app-root.js. and i find these lines
   /**
             * On iOS 12.2 there is a bug that
             * prevents pointer-events from being
             * re-enabled when removing the
             * disable-scroll class.
             */
            const plaform = this._plt;
            plaform.raf(() => {
                this.setElementStyle('z-index', '1');
                plaform.raf(() => {
                    this.setElementStyle('z-index', null);
                });
            });

**Pull request merged**
